#+OPTIONS: ^:nil
#+OPTIONS: toc:nil
#+OPTIONS: num:t
#+OPTIONS: H:5

* Introduction :ignore:
  The Stanc3 compiler can attempt to optimize a Stan program as it is compiled.
  The optimized program has the same behavior as the unoptimized program, but it may be faster, more memory efficient, or more numerically stable.
  
  This section introduces the available optimization options and describes their effect.

  You can see a printout of a representation of the Stan program after the optimizations have been applied with the Stanc3 command-line option ~--debug-optimized-mir-pretty~.
  You can see an analogous representation of the program before optimizations have been applied with ~--debug-transformed-mir-pretty~.
  
* Optimization levels
  To turn on optimizations, the user specifies the desired optimization /level/.
  The level specifies the set of optimizations which are turned on.
  Optimizations which are turned on are then applied in a specific order, and some are applied repeatedly.

  Optimization levels are specified by the numbers 0-4:
  * *0*
    No optimizations are applied.
  * *1*
    Only optimizations which are simple to understand, do not dramatically change the program, and are unlikely noticeably slow down compile times are applied.
  * *2*
    All optimizations which are unlikely to be numerically different than the unoptimized program are applied.
    Some code transformations, such as replacing ~log(1-x)~ with the builtin ~log1m(x)~, may result in slight numerical differences that are detectable when sampling from the program with a fixed random seed.
    Those transformations are avoided.
  * *3*
    All optimizations are applied.
  
  The levels include these optimizations:
  * *0*
    None
  * *1*
    * Dead code elimination
    * Auto-differentiation level optimization
  * *2*
    * Function inlining*
    * Static loop unrolling
    * One step loop unrolling
    * Constant propagation*
    * Expression propagation*
    * Copy propagation*
    * Dead code elimination
    * Partial evaluation*
    * Lazy code motion*
    * Auto-differentiation level optimization
    *: A more numerically stable version of this optimization.
  * *3*
    * Function inlining
    * Static loop unrolling
    * One step loop unrolling
    * Constant propagation
    * Expression propagation
    * Copy propagation
    * Dead code elimination
    * Partial evaluation
    * Lazy code motion
    * Auto-differentiation level optimization
* Optimization documentation
** Function inlining
   Function inlining replaces each function call to each user-defined function ~f~ with the body of ~f~.
   It does this by copying the function body to the call site and doing the appropriate renaming of the argument variables.
   This can speed up a program by avoiding the overhead of a function call and providing more opportunities for further optimizations (such as partial evaluation).
   
 Example Stan program:
 #+INCLUDE: "examples/fi-ex.stan" src

 Program after function inlining (simplified from the output of ~--debug-optimized-mir-pretty~):
 #+INCLUDE: "examples/fi-ex.opt-mir.edit" src

** Static loop unrolling
   <<sec:static-unroll>>
   Static loop unrolling takes a loop that has a predictable number of iterations ~X~ and replaces it by writing out the loop body ~X~ times.
   The loop index in each repeat is replaced with the appropriate constant.
   This can speed up a program by avoiding the overhead of a loop and providing more opportunities for further optimizations (such as partial evaluation).
   
 Example Stan program:
 #+INCLUDE: "examples/slu-ex.stan" src

 Program after static loop unrolling (simplified from the output of ~--debug-optimized-mir-pretty~):
 #+INCLUDE: "examples/slu-ex.opt-mir.edit" src

** One step loop unrolling
   One step loop unrolling is similar to [[sec:static-unroll][static loop unrolling]], but it only 'unrolls' the first iteration of a loop, and can therefore work even when the total number of iterations is not predictable.
   This can speed up a program by providing more opportunities for further optimizations such as partial evaluation and lazy code motion.
   
 Example Stan program:
 #+INCLUDE: "examples/oslu-ex.stan" src

 Program after one step static loop unrolling (simplified from the output of ~--debug-optimized-mir-pretty~):
 #+INCLUDE: "examples/oslu-ex.opt-mir.edit" src

** Constant propagation
   Constant propagation replaces uses of a variable which is known to have a constant value ~C~ with that constant ~C~.
   This removes the overhead of looking up the variable, and also makes many other optimizations possible (such as static loop unrolling and partial evaluation).
   
 Example Stan program:
 #+INCLUDE: "examples/cp-ex.stan" src

 Program after constant propagation (simplified from the output of ~--debug-optimized-mir-pretty~):
 #+INCLUDE: "examples/cp-ex.opt-mir.edit" src

** Expression propagation
   <<sec:expression-prop>>
   Constant propagation replaces uses of a variable which is known to have a constant value ~E~ with that constant ~E~.
   This often results in recalculation of the expression, but provides more opportunities for further optimizations such as partial evaluation.
   Expression propagation is always followed by [[sec:lcm][lazy code motion]] to avoid unnecessarily recomputing expressions.
   
   Example Stan program:
   #+INCLUDE: "examples/ep-ex.stan" src
   
   Program after expression propagation (simplified from the output of ~--debug-optimized-mir-pretty~):
   #+INCLUDE: "examples/ep-ex.opt-mir.edit" src
** Copy propagation
   Copy propagation is similar to [[sec:expression-prop][expression propagation]], but only propagates variables rather than arbitrary expressions.
   This can reduce the complexity of the code for other optimizations such as expression propagation.

   Example Stan program:
   #+INCLUDE: "examples/copy-ex.stan" src
   
   Program after copy propagation (simplified from the output of ~--debug-optimized-mir-pretty~):
   #+INCLUDE: "examples/copy-ex.opt-mir.edit" src
** Dead code elimination
   Dead code is code that does not have any effect on the behavior of the program.
   Code is not dead if it affects ~target~, the value of any outside-observable variable like transformed parameters or generated quantities, or side effects such as print statements.
   Removing dead code can speed up a program by avoiding unnecessary computations.

   Example Stan program:
   #+INCLUDE: "examples/dce-ex.stan" src
   
   Program after dead code elimination (simplified from the output of ~--debug-optimized-mir-pretty~):
   #+INCLUDE: "examples/dce-ex.opt-mir.edit" src
** Partial evaluation
   Partial evaluation searches for expressions that can be replaced with a faster, simpler, more memory efficient, or more numerically stable expression that has the same meaning.

   Example Stan program:
   #+INCLUDE: "examples/pe-ex.stan" src
   
   Program after partial evaluation (simplified from the output of ~--debug-optimized-mir-pretty~):
   #+INCLUDE: "examples/pe-ex.opt-mir.edit" src
** Lazy code motion
   <<sec:lcm>>
   Lazy code motion rearranges the statements and expressions in a program with the goals of:
   * Avoiding computing expressions more than once, and
   * Computing expressions as late as possible (to minimize the strain on the working memory set).
   To accomplish these goals, lazy code motion will perform optimizations such as:
   * Moving a repeatedly calculated expression its own variable (also referred to as /common-subexpression elimination/)
   * Moving an expression outside of a loop, if it doesn't need to be in the loop (also referred to as /loop-invariant code motion/)
   Lazy code motion can make some programs significantly more efficient by avoiding redundant or early computations.

   Example Stan program:
   #+INCLUDE: "examples/lcm-ex.stan" src
   
   Program after lazy code motion (simplified from the output of ~--debug-optimized-mir-pretty~):
   #+INCLUDE: "examples/lcm-ex.opt-mir.edit" src
** Auto-differentiation level optimization
   Stan variables can have two auto-differentiation (AD) /levels/: AD or non-AD.
   AD variables carry gradient information with them, which allows Stan to calculate the log-density gradient, but they also have more overhead than non-AD variables.
   It is therefore inefficient for a variable to be AD unnecessarily.
   AD-level optimization sets every variable to be non-AD unless its gradient is necessary.

   Example Stan program:
   #+INCLUDE: "examples/adl-ex.stan" src
   
   Program after AD-level optimization (simplified from the output of ~--debug-optimized-mir-pretty~):
   #+INCLUDE: "examples/adl-ex.opt-mir.edit" src
